DI for static classes (ICrypto and IBinarySerialization)
CityOfZion/neo-sharp pull request #228
Opened 2018-07-13 07:25 UTC by ricardoak25

Resolve extension injections problems of ICrypto and IBinarySerialization classes, (and other static methods)

2018-07-13 09:56 UTC, shargon commented
@aboimpinto @osmirnov what do you think about this solution, i like it

2018-07-13 09:57 UTC, shargon approved these changes

2018-07-13 14:51 UTC, osmirnov commented
There are many problems with this approach but I tend to approve this if IStaticDI is renamed to ICryptoInitializer and StaticDI to CryptoInitializer. These initializers have to be introduced per problematic dependency. Maybe, in future we will discover some IContainerInitializer interface for DI container and call all classes implementing that automatically.

2018-07-13 14:52 UTC, osmirnov reviewed
There are many problems with this approach but I tend to approve this if IStaticDI is renamed to ICryptoInitializer and StaticDI to CryptoInitializer. These initializers have to be introduced per problematic dependency. Maybe, in future we will discover some IContainerInitializer interface for DI container and call all classes implementing that automatically.

2018-07-13 14:59 UTC, shargon requested changes
Rename the classes according to @osmirnov comment

2018-07-13 19:45 UTC, aboimpinto commented
I can see this could be a way to solve the issue but it's not a solution... it is just a patch

2018-07-16 08:53 UTC, ricardoak25 commented
All changes its done.

2018-07-17 09:29 UTC, shargon commented on src/NeoSharp.BinarySerialization/BinarySerializer.cs
> +        public static IBinarySerializer Default { get; private set; }
Initialize by default, because you could use this class without injection

2018-07-17 09:29 UTC, shargon commented on src/NeoSharp.BinarySerialization/BinaryDeserializer.cs
> +        public static IBinaryDeserializer Default { get; private set; }
Initialize by default, because you could use this class without injection

2018-07-17 09:31 UTC, shargon commented on src/NeoSharp.BinarySerialization/SerializationHooks/IBinaryCustomSerializable.cs
> -        object Deserialize(IBinaryDeserializer deserializer, BinaryReader reader, Type type, BinarySerializerSettings settings = null);
This should not be removed

2018-07-18 03:08 UTC, merged